### PR TITLE
add reference documentation

### PR DESCRIPTION
**Pull request by marti1125**
:)

### CODE REVIEW

**Comment by deleteman** [comment]
Hey, thanks for the PR @marti1125 , but I have a couple of questions:

1- What's exactly the point behind it? I see you added a Parsdown library, and copied the readme file into a docs folder, am I missing something else?
2- I see you committed a couple of files ending with "~", are those temp files? And yo also committed the logs.txt file.

Regarding the second point, if those are indeed tmpe file, please remove them from the PR (as well as the logs.txt file)

**Comment by marti1125** [comment]
1- I added Parsdown library for read markdown, when you copy and paste makiavelo in wamp(windows) you can read the information about it.

./markdown.php doesn't work in windows :(

2- I deleted some temporary files.

**Comment by deleteman** [comment]
Great, now it makes more sense! I'll test it locally and merge it if everything seems fine. Thanks for the  PR again!

Also, if you're in Windows, instead of doing "./markdown.php" you should try "php markdown.php", that should work.

**Comment by marti1125** [comment]
@deleteman  any news about that

**Comment by marti1125** [comment]
Thanks :), I hope to help you more,  I have experience with cakephp but now I am working as a java developer(Web)

**Comment by deleteman** [comment]
@marti1125 thanks for the PR!

**Comment by deleteman** [comment]
@marti1125 Awesome! I look forward to your comments/help with this project! :)

**Pull request merged**
